WITH remdup_stage AS (
 SELECT
 *,
 ROW_NUMBER() OVER (PARTITION BY SRC_DL, AR_ID ORDER BY SRC_DL, AR_ID) AS row_num
 FROM V438S0P1
 QUALIFY row_num = 1
),
join_stage AS (
 SELECT
 a.*,
 b.*
 FROM V438S1P1 a
 LEFT OUTER JOIN V438S1P2 b
 ON a.SRC_DL = b.SRC_DL AND a.AR_ID = b.AR_ID
),
sort_stage AS (
 SELECT
 *
 FROM V438S10P1
 ORDER BY SRC_DL, AR_ID
),
transform_stage AS (
 SELECT
 mov_AR_X_R_HIGHEST.HIGHEST_FCY_ID AS AR_ID,
 'Y' AS HIGHEST_FCY_IN_HRY
 FROM V438S2P1 mov_AR_X_R_HIGHEST
),
final_stage AS (
 SELECT
 mov_FCY_AR_IDENTN.SYS_VLD_FROM_TMS AS DATE_FROM,
 mov_FCY_AR_IDENTN.UNDRL_AR_ID AS AR_ID,
 mov_FCY_AR_IDENTN.SYS_VLD_TO_TMS AS DATE_TO,
 COALESCE(mov_FCY_AR_IDENTN.HIGHER_FCY_RK, mov_FCY_AR_IDENTN.FCY_RK) AS HIGHER_FCY_RK,
 COALESCE(mov_FCY_AR_IDENTN.HIGHEST_FCY_RK, mov_FCY_AR_IDENTN.FCY_RK) AS HIGHEST_FCY_RK,
 CASE
 WHEN mov_FCY_AR_IDENTN.HLEAF = 1 THEN 'Y'
 WHEN mov_FCY_AR_IDENTN.HLEAF = 0 THEN 'N'
 WHEN mov_FCY_AR_IDENTN.HIGHEST_FCY_IN_HRY = 'Y' THEN 'N'
 ELSE 'Y'
 END AS LOWEST_LVL_IND,
 mov_FCY_AR_IDENTN.AR_IDENTN_NM AS FCY_VORTEX_ID,
 timestamp_from_ustring(DSJobStartTimestamp) AS SYS_INRT_TMS
 FROM V438S24P1 mov_FCY_AR_IDENTN
)
SELECT
 DATA_DT,
 FCY_ID
FROM final_stage